services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build: .
    container_name: user-api
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/users
    depends_on:
      - mongo

volumes:
  mongo-data:
